TIMESTAMP_COL = 'TIMESTAMP'
TIMESTAMP_IDX = 0

TEMP_C_COL = 'TEMP_C'
TEMP_C_IDX = 1

FRAME_W_COL = 'FRAME_W'
FRAME_W_IDX = 2

FRAME_H_COL = 'FRAME_H'
FRAME_H_IDX = 3

DATAFRAME_COLUMNS = [TIMESTAMP_COL, TEMP_C_COL, FRAME_W_COL, FRAME_H_COL]